config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :find_flat, except: [ :index, :new, :create ]
  # only: [ :show, :update, :edit, :destroy ]
  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flats_path
    else
      render :new
    end
  end

  def update
    @flat.update(flat_params)
    redirect_to flat_path(@flat)
  end

  def destroy
    @flat.destroy
    redirect_to flats_path
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests, :rating)
  end

  def find_flat
    @flat = Flat.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for(@flat) do |r| %>
  <%= r.input :name %>
  <%= r.input :address %>
  <%= r.input :description %>
  <%= r.input :price_per_night %>
  <%= r.input :number_of_guests %>
  <%= r.input :rating %>
  <%= r.submit %><br>



<% end %>

app/views/flats/edit.html.erb
<h1> Edit a flat </h1>
<%= render 'form', flat: @flat %>

app/views/flats/index.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-12">
<h2> All our Flats (<%= @flats.count %>)</h2>
    </div>
  </div>

<h3></h3>
<div class="row">
<% @flats.each do |f| %>
      <div class="col-4">
        <div class="flat-card">
<img src="..." class="card-img-top" alt="...">
         <div class="flat-card-content">
            <div class="flat-card-title">
 <%= f.name %> 
             </div>
<%= f.address %>

            <div class="flex">
              <div class="flex">
<i class="material-icons">attach_money</i><%= f.price_per_night %>

              </div>
              <div class="flex ml-3">
<i class="material-icons">people</i><%= f.number_of_guests %>

              </div>
            </div>
          </div>
          <div class="flat-card-actions">
<%= f.rating %>

<%= link_to 'More info', flat_path(f) %>
<%= link_to 'Edit', edit_flat_path(f) %>
<%= link_to 'Remove', flat_path(f), method: :delete  %>

          </div>
        </div>
      </div>
<% end %>

  </div>

</div>

app/views/flats/new.html.erb
<h1> Add a new flat </h1>

<%= render 'form' %>

app/views/flats/show.html.erb
<div  class="card" >
<h2> <%=  @flat.name %> </h2>
<p> <%=  @flat.address %> </p></div>
<div  class="card" > <h2> Acerca de este hospedaje...</h2>
<%=  "⭐"*@flat.rating.to_i %> 
<%=  @flat.description %> </div>
<div  class="card" >
<h2> Detalles</h2>
<i class="material-icons">attach_money</i><%= @flat.price_per_night %>
<i class="material-icons">people</i><%= @flat.number_of_guests %></div>
</div>


     
    <div>
<%= link_to "Edit this flat", edit_flat_path(@flat), class: "btn btn-primary" %>
<%= link_to "Back to all flats", flats_path, class: "btn btn-primary" %> 
<%= link_to "Remove", flat_path(@flat), method: :delete, data: { confirm: "Esta seguro?" } %>

</div>

<div>
</div>

<div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  </head>

  <body>
  <div class="container">
    <div class="navbar navbar-light bg-secondary justify-content-left">
      <span>RailsSimpleAirbnb</span>>
      <%= link_to 'Home', flats_path, class: "btn btn-secondary" %>
      <%= link_to 'Flats', flats_path, class: "btn btn-secondary" %>
      <%= link_to 'Add flat', new_flat_path, class: "btn tertiary" %>
    </div>
    <div classs="row">
     <%= yield %>
    </div>
  </body>
</html>